server:
  http_listen_port: 9080
  log_level: debug

positions:
  filename: /tmp/positions.yaml


clients:
  - url: http://loki:3100/loki/api/v1/push



scrape_configs:
  - job_name: 'outcurr'
    static_configs:
      - targets: ['outcurr.web.1:9092']
        labels:
          job: 'outcurr'
          __path__: /var/log/outcome-curr-mgmt/*.log
    pipeline_stages:
    - logfmt:
        mapping:
          component:
    - labels:
        component:
        